### ISSUE TITLE
Xml convert error while InvokeIA

### ISSUE THREAD

**Issue by aimuke** [OpenTOSCA/container#6] opened 2016-06-01 08:37 UTC
Hi,
     I'm testing to invoke IA after i imported the csar. The invoke successed after I started the container. But I found if i continuously invoke IA, there will be an issue .This issue happens after a few invokes while I invoke IA in a loop. Once this issue happens it will happen every time when i invoke IA. And when i add a time interval between two invokes, this issue never happens.

Hope u may help me with this problem, thx.

the exceptoins like below:

> 2016-06-01 14:56:28,497  ERROR  o.a.camel.processor.DefaultErrorHandler   Failed delivery for (MessageId: ID-host-10-10-1-67-45893-1464763858788-4-54 on ExchangeId: ID-host-10-10-1-67-45893-1464763858788-4-55). Exhausted after delivery attempt: 1 caught: java.lang.ClassCastException: org.opentosca.model.tosca.TInterface cannot be cast to com.sun.xml.internal.bind.v2.runtime.unmarshaller.DomLoader$State

	at org.opentosca.toscaengine.xmlserializer.service.impl.XMLSerializer.unmarshal(XMLSerializer.java:282) ~[na:na]
	at org.opentosca.toscaengine.service.impl.toscareferencemapping.ToscaReferenceMapper.getJAXBReference(ToscaReferenceMapper.java:335) ~[na:na]
	at org.opentosca.toscaengine.service.impl.ToscaEngineServiceImpl.getNodeTypeOfNodeTemplate(ToscaEngineServiceImpl.java:1412) ~[na:na]
	at org.opentosca.siengine.service.impl.SIEngineServiceImpl.invokeIA(SIEngineServiceImpl.java:149) ~[na:na]

**Comment by nyuuyn** [comment] 2016-06-03 10:19
Hi,

could you give us the CSAR you used for reproducing the issue? Also, is the IA a script or a Webservice?

Regards

**Comment by aimuke** [comment] 2016-06-06 06:15
Thanks for you reply.
The IA is a Webservice. how should i give you the CSAR?

**Comment by nyuuyn** [comment] 2016-06-06 14:18
Hi,

you could push it to a github repo or something like dropbox. If the CSAR is not too large you could also send it to me in an email.

Regards

**Comment by aimuke** [comment] 2016-06-08 06:42
Hi,

it seems like that i can not upload a csar file to the github repo. when i upload the csar file, there is a error like ''.

the csar is about 6M. maybe i could send it to you in email. could you give me ur email address. thanks.

Regards

**Comment by nyuuyn** [comment] 2016-06-09 09:02
Hi,

here ya go: kalman.kepes@iaas.uni-stuttgart.de

Regards

**Comment by aimuke** [comment] 2016-06-12 06:55
Hi,

i have send the csar to you by email. 

there are 3 files in the attachment. one is the csar, and the rest two are the test code and test param.
i use the test code to call wso2 to start a workflow, and webservice IA will be called by the workflow.

hope you may help me to fix out this problem. 

Regards.

**Comment by nyuuyn** [comment] 2016-06-15 12:26
Sorry, but i didn't get any mail till now
Can you try to send it again?

Regards

**Comment by aimuke** [comment] 2016-06-29 06:03
sorry, last time my colleague forgot to send u the email, i have all ready asked him to send u the email again. would u please check the email. thx.

**Comment by nyuuyn** [comment] 2016-07-01 19:11
I added a fix unto the maven branch. I tested it against your CSAR and some of ours. It seems to work now, could you give us feedback whether it works on your side?

Regards

**Comment by aimuke** [comment] 2016-07-14 03:35
Hi.
For this days, i did some test about this issue. it seems this issue has been fixed. i did not get this error now. thx.

Regards

**Comment by nyuuyn** [comment] 2016-07-14 12:03
Seems that the issue is fixed, closing issue.

**Closed by nyuuyn** 2016-07-14 12:03 UTC
